### ISSUE TITLE
No Word List...

### ISSUE THREAD

**Issue by krambrose** [openforeveryone/WordSearchCreator#3] opened 2024-04-22 11:01 UTC
I feel like such an idiot even typing this because I read the docs, I checked the settings out, I checked the images out.  But, my program is simply NOT showing my word list.  I have SHOW WORDS LIST checked.  I've tried different font sizes, I've tried different different widths and nothing... LOL.  

![idk bro](https://github.com/openforeveryone/WordSearchCreator/assets/19415506/e652e8a6-e735-4941-a533-ffdbfd9e08a4)

**Comment by mattwellings** [comment] 2024-04-22 16:25
Thank you for posting this issue, I believe this may be a limitation I am aware of and should have documented years ago.

If there are too many words to fit in the space below the word search using the current font then it will simply not draw the word list. I hope to add multi-page support in future but this could be a while coming (alternatively I could make it draw just part of the word list and pop up a warning similar to what happens when the grid is too small). 
For now you have the following options: 
- Decrease the font size of the word search and/or the word list until it displays.
- Copy the word list into a word processor to print separately
- Copy the word search into a word processor which will allow you to place the words on multiple pages (this can be done by exporting it as an SVG then inserting it as an image). 

Alternatively reduce the number of words in the word search or the height of the word search. You may want to do this just to check that this really is the cause of the issue you are seeing. If, for example, you remove all the words but one then click "Create/Shuffle" and still nothing shows below the word search then I am incorrect about the cause of your issue.

I will leave this issue open and close it once I have added multi page support.

**Comment by mattwellings** [comment] 2024-05-12 20:22
I have just released a new version (v1.3) which adds multi-page support. If there are too many words to fit in the space below the word search, instead of the whole word list dispersing, those that that can fit will shown below the word search on the first page and the rest will be printed on additional pages.

**Closed as completed by mattwellings** 2024-05-12 20:22 UTC
